services:
  marketplace:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - PRIVATE_KEY_PEM=${PRIVATE_KEY_PEM}
      - PUBLIC_KEY_PEM=${PUBLIC_KEY_PEM}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /home/${USER}/.pgdata:/var/lib/postgresql/data/pgdata
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    tty: true
    stdin_open: true
